name: AppSec Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_scan:
    name: Run SAST Scan
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Скачиваем код репозитория на виртуальную машину GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Запускаем бесплатный сканер Semgrep
      - name: Semgrep SAST Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: p/default # Используем стандартный набор правил для поиска уязвимостей
        #env:
          #SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} # Опционально, можно без него

      # Шаг 3: Проверяем, не забыли ли мы секреты в коде (Trufflehog)
      - name: TruffleHog OSS Scan
        uses: trufflesecurity/trufflehog-actions-scan@v3.82.0
        with:
          base: ${{ github.event.repository.default_branch }}
          head: HEAD