name: AppSec Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_scan:
    name: Run Security Tools
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Скачиваем ВСЮ историю кода (нужно для TruffleHog)
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      # Шаг 2: Сканер секретов по официальному гайду
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55
        with:
          extra_args: --results=verified,unverified,unknown --filter-entropy=3.0 --no-github-actions --log-level=0

      

      # Шаг 3: Статический анализ кода (Semgrep)
      - name: Semgrep SAST Scan (OSS Mode)
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" semgrep/semgrep semgrep scan --config=p/default --error